font_family = "Cascadia Mono"
font_size = 18
copy_on_select = true
cursor_style = "block"

[theme]
background = "#0B1120"
foreground = "#E9EEF9"
accent = "#8F53FF"
muted = "#8A94A8"
status_background = "#1A2131"
selection = "#355EA6"

[[profiles]]
name = "pwsh"
command = "pwsh.exe"
arguments = ["-NoLogo"]

[[profiles]]
name = "bash"
command = "wsl.exe"
arguments = []

[[profiles]]
name = "server logs"
command = "cmd.exe"
arguments = []
