# Built-in Wsh theme: Material Ocean
[colors]
background  = "#0f111a"
foreground  = "#a6accd"
cursor      = "#ffcc00"
selection   = "#1f2233"
black       = "#000000"
red         = "#ff5370"
green       = "#c3e88d"
yellow      = "#ffcb6b"
blue        = "#82aaff"
magenta     = "#c792ea"
cyan        = "#89ddff"
white       = "#ffffff"
bright_black   = "#546e7a"
bright_red     = "#ff5370"
bright_green   = "#c3e88d"
bright_yellow  = "#ffcb6b"
bright_blue    = "#82aaff"
bright_magenta = "#c792ea"
bright_cyan    = "#89ddff"
bright_white   = "#ffffff"
