# Built-in Wsh theme: Material Cyber Dark
[colors]
background  = "#0d0f14"
foreground  = "#e2e6f0"
cursor      = "#4f8ef7"
selection   = "#27324a"
black       = "#13161e"
red         = "#f7604f"
green       = "#3dd68c"
yellow      = "#f7b84f"
blue        = "#4f8ef7"
magenta     = "#a97ff7"
cyan        = "#4fcff7"
white       = "#e2e6f0"
bright_black   = "#40465c"
bright_red     = "#ff7a6d"
bright_green   = "#63e5a4"
bright_yellow  = "#ffd077"
bright_blue    = "#77a7ff"
bright_magenta = "#bd9aff"
bright_cyan    = "#7de0ff"
bright_white   = "#ffffff"
