"""Embed Ghostty's src/terminal/res/rgb.txt as a C++ string literal.

Upstream does `const data = @embedFile("res/rgb.txt")` and parses the text at
compile time. C++14 cannot read a file at compile time, so this writes the
file's bytes into src/terminal/res/x11_rgb_data.inc, and x11_color in
color.hpp parses that text with upstream's line logic on first use.

The data is the rgb.txt file from the X11 project, under the MIT/X11 license.

Usage: python tools/gen_x11_rgb.py <path-to-rgb.txt>
"""

import os
import sys


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 2

    data = open(sys.argv[1], 'rb').read()
    out_path = os.path.join(os.path.dirname(__file__), '..', 'src', 'terminal',
                            'res', 'x11_rgb_data.inc')
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    lines = ['/* Generated by tools/gen_x11_rgb.py from Ghostty',
             ' * src/terminal/res/rgb.txt, which is the rgb.txt file from the X11',
             ' * project (https://gitlab.freedesktop.org/xorg/app/rgb), MIT/X11',
             ' * license. Do not edit by hand. */',
             '']

    # One C string literal per source line, so the text survives exactly,
    # byte for byte, including its tabs and line endings. Octal escapes,
    # not hex: a hex escape runs on through any following hex digit, so a
    # tab before "aqua" would swallow the "a".
    parts = data.split(b'\n')
    if parts and parts[-1] == b'':
        parts.pop()
    for raw in parts:
        escaped = ''.join(
            chr(b) if 0x20 <= b < 0x7f and chr(b) not in '"\\?' else '\\%03o' % b
            for b in raw)
        lines.append('"%s\\n"' % escaped)

    with open(out_path, 'w', encoding='ascii', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')

    print('wrote', os.path.normpath(out_path), len(data), 'bytes')
    return 0


if __name__ == '__main__':
    sys.exit(main())
