#!/usr/bin/env python
"""Regenerate docs/GHOSTTY_PORT_LEDGER.md from a Ghostty checkout.

The ledger is the file-by-file work list for porting Ghostty to Wisp. It is
generated rather than hand-written so that "what is left" is always measured
against real upstream source instead of memory.

Usage:

    git clone --depth 1 https://github.com/ghostty-org/ghostty.git /tmp/ghostty
    python tools/gen_port_ledger.py /tmp/ghostty

Status for each file is preserved across regeneration: the script reads the
existing ledger and carries forward any row not marked "todo", so marking a
module done survives the next upstream refresh.
"""

import os
import re
import subprocess
import sys

LEDGER = os.path.join("docs", "GHOSTTY_PORT_LEDGER.md")

# Modules that a Windows port does not need to reproduce, with the reason.
# These are still listed in the ledger, marked "n/a", so the count stays honest.
NOT_APPLICABLE = {
    "apprt/gtk": "Linux GTK application runtime",
    "apprt/embedded": "macOS/iOS embedding shim",
    "renderer/metal": "Apple Metal backend",
    "build": "Zig build system plumbing",
    "benchmark": "upstream micro-benchmarks",
    "synthetic": "benchmark data generation",
}


def upstream_revision(root):
    try:
        out = subprocess.check_output(
            ["git", "-C", root, "log", "-1", "--format=%H %ad", "--date=short"],
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except Exception:
        return "unknown"


def module_of(rel):
    parts = rel.split("/")
    if len(parts) == 1:
        return "src"
    if len(parts) == 2:
        return parts[0]
    return parts[0] + "/" + parts[1]


def load_existing_status():
    """Carry forward any status the previous ledger recorded."""
    status = {}
    if not os.path.exists(LEDGER):
        return status
    row = re.compile(r"^\|\s*`([^`]+)`\s*\|[^|]*\|\s*([^|]+?)\s*\|")
    with open(LEDGER, encoding="utf-8") as f:
        for line in f:
            m = row.match(line)
            if m:
                status[m.group(1)] = m.group(2).strip()
    return status


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_port_ledger.py <path-to-ghostty-checkout>")
    root = sys.argv[1]
    src = os.path.join(root, "src")
    if not os.path.isdir(src):
        sys.exit("no src/ directory in {}".format(root))

    prior = load_existing_status()

    files = []
    for dirpath, _dirs, names in os.walk(src):
        for n in names:
            if not n.endswith(".zig"):
                continue
            full = os.path.join(dirpath, n)
            rel = os.path.relpath(full, src).replace(os.sep, "/")
            with open(full, "rb") as f:
                lines = sum(1 for _ in f)
            files.append((rel, lines))
    files.sort()

    modules = {}
    for rel, lines in files:
        modules.setdefault(module_of(rel), []).append((rel, lines))

    total_lines = sum(n for _, n in files)
    todo_lines = 0
    na_lines = 0
    done_lines = 0

    wip_lines = 0

    for rel, lines in files:
        mod = module_of(rel)
        st = prior.get(rel)
        if st == "n/a":
            na_lines += lines
        elif st == "done":
            done_lines += lines
        elif st == "wip":
            # A partially ported file is not ported. Counting it as done
            # would overstate progress by the whole file's length, so it
            # stays in the remaining total and is reported separately.
            wip_lines += lines
            todo_lines += lines
        elif mod in NOT_APPLICABLE:
            na_lines += lines
        else:
            todo_lines += lines

    out = []
    out.append("# Ghostty port ledger")
    out.append("")
    out.append("Generated by `tools/gen_port_ledger.py`. Do not edit the tables by")
    out.append("hand except to change a **status** cell — those are carried forward")
    out.append("when the ledger is regenerated against a newer upstream.")
    out.append("")
    out.append("Upstream: <https://github.com/ghostty-org/ghostty>  ")
    out.append("Revision: `{}`  ".format(upstream_revision(root)))
    out.append("License: MIT, (c) 2024 Mitchell Hashimoto and Ghostty contributors")
    out.append("")
    out.append("## Totals")
    out.append("")
    out.append("| | Files | Lines |")
    out.append("|---|---:|---:|")
    out.append("| Upstream `src/` (Zig) | {} | {} |".format(len(files), total_lines))
    out.append("| Ported | - | {} |".format(done_lines))
    out.append("| Not applicable to a Windows port | - | {} |".format(na_lines))
    out.append("| Remaining | - | {} |".format(todo_lines))
    out.append("| ...of which partially ported | - | {} |".format(wip_lines))
    out.append("")
    out.append("Status values: `todo`, `wip`, `done`, `n/a`. A `wip` file counts")
    out.append("toward *remaining*, not ported — a partially ported file is not")
    out.append("ported, and counting it as done would overstate progress by the")
    out.append("whole file's length.")
    out.append("")
    out.append("## Modules")
    out.append("")
    out.append("| Module | Files | Lines | Note |")
    out.append("|---|---:|---:|---|")
    for mod in sorted(modules, key=lambda m: -sum(n for _, n in modules[m])):
        entries = modules[mod]
        note = NOT_APPLICABLE.get(mod, "")
        out.append("| `{}` | {} | {} | {} |".format(
            mod, len(entries), sum(n for _, n in entries), note))
    out.append("")

    for mod in sorted(modules, key=lambda m: -sum(n for _, n in modules[m])):
        entries = sorted(modules[mod], key=lambda e: -e[1])
        out.append("### `{}`".format(mod))
        out.append("")
        if mod in NOT_APPLICABLE:
            out.append("_Not applicable: {}._".format(NOT_APPLICABLE[mod]))
            out.append("")
        out.append("| File | Lines | Status |")
        out.append("|---|---:|---|")
        for rel, lines in entries:
            default = "n/a" if mod in NOT_APPLICABLE else "todo"
            out.append("| `{}` | {} | {} |".format(
                rel, lines, prior.get(rel, default)))
        out.append("")

    os.makedirs("docs", exist_ok=True)
    with open(LEDGER, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))

    print("wrote {}".format(LEDGER))
    print("  {} files, {} lines upstream".format(len(files), total_lines))
    print("  remaining: {} lines".format(todo_lines))


if __name__ == "__main__":
    main()
