#!/usr/bin/env python
"""Compute a dependency-ordered port sequence for a Ghostty module.

Reading the import graph matters because Zig tolerates import cycles that a
C++ header cannot: a cycle has to be broken with a forward declaration, and
you want to know that before you start writing, not halfway through a file.

Writes docs/GHOSTTY_PORT_ORDER.md.

Usage:

    python tools/gen_port_order.py <path-to-ghostty-checkout> [module]

`module` defaults to "terminal".
"""

import os
import re
import sys

OUT = os.path.join("docs", "GHOSTTY_PORT_ORDER.md")
IMPORT_RE = re.compile(r'@import\("([A-Za-z0-9_./]+\.zig)"\)')


def collect(src, module):
    """Map each module-local .zig file to the module-local files it imports."""
    root = os.path.join(src, module)
    graph = {}
    external = {}

    for dirpath, _dirs, names in os.walk(root):
        for n in names:
            if not n.endswith(".zig"):
                continue
            full = os.path.join(dirpath, n)
            rel = os.path.relpath(full, root).replace(os.sep, "/")

            with open(full, encoding="utf-8", errors="replace") as f:
                text = f.read()

            deps = set()
            ext = set()
            here = os.path.dirname(rel)
            for imp in IMPORT_RE.findall(text):
                if imp.startswith("../"):
                    ext.add(imp)
                    continue
                # Resolve relative to the importing file's directory.
                target = os.path.normpath(os.path.join(here, imp)).replace(os.sep, "/")
                if os.path.exists(os.path.join(root, target)):
                    deps.add(target)
                else:
                    ext.add(imp)

            deps.discard(rel)
            graph[rel] = deps
            external[rel] = ext

    return graph, external


def line_counts(src, module, graph):
    root = os.path.join(src, module)
    counts = {}
    for rel in graph:
        with open(os.path.join(root, rel), "rb") as f:
            counts[rel] = sum(1 for _ in f)
    return counts


def layer(graph):
    """Kahn's algorithm, emitting one layer per round.

    Whatever remains when no node has all its dependencies satisfied is
    involved in a cycle, so it is reported separately instead of being
    forced into an order that does not exist.
    """
    remaining = {k: set(v) for k, v in graph.items()}
    done = set()
    layers = []

    while remaining:
        ready = sorted(k for k, deps in remaining.items() if deps <= done)
        if not ready:
            break
        layers.append(ready)
        done.update(ready)
        for k in ready:
            del remaining[k]

    return layers, remaining


def find_cycles(remaining):
    """Report the concrete 2-cycles, which are the ones worth naming."""
    pairs = set()
    for a, deps in remaining.items():
        for b in deps:
            if b in remaining and a in remaining.get(b, ()):
                pairs.add(tuple(sorted((a, b))))
    return sorted(pairs)


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_port_order.py <path-to-ghostty-checkout> [module]")

    root = sys.argv[1]
    module = sys.argv[2] if len(sys.argv) > 2 else "terminal"
    src = os.path.join(root, "src")
    if not os.path.isdir(os.path.join(src, module)):
        sys.exit("no src/{} in {}".format(module, root))

    graph, external = collect(src, module)
    counts = line_counts(src, module, graph)
    layers, remaining = layer(graph)

    out = []
    out.append("# Ghostty port order — `{}`".format(module))
    out.append("")
    out.append("Generated by `tools/gen_port_order.py`.")
    out.append("")
    out.append("Files are grouped into layers: everything in a layer depends only")
    out.append("on layers above it, so a layer can be ported in any internal order.")
    out.append("")

    total = sum(counts.values())
    ordered = sum(counts[f] for lz in layers for f in lz)
    out.append("| | Files | Lines |")
    out.append("|---|---:|---:|")
    out.append("| Total in `{}` | {} | {} |".format(module, len(graph), total))
    out.append("| Orderable | {} | {} |".format(
        sum(len(lz) for lz in layers), ordered))
    out.append("| In a cycle | {} | {} |".format(
        len(remaining), total - ordered))
    out.append("")

    if remaining:
        out.append("## Cycles")
        out.append("")
        out.append("Zig resolves these lazily; a C++ header cannot. Each pair needs a")
        out.append("forward declaration, with the out-of-line definitions placed in")
        out.append("whichever header is ported second.")
        out.append("")
        cycles = find_cycles(remaining)
        if cycles:
            out.append("| A | B |")
            out.append("|---|---|")
            for a, b in cycles:
                out.append("| `{}` | `{}` |".format(a, b))
            out.append("")

        out.append("All files still unresolved when ordering stopped:")
        out.append("")
        out.append("| File | Lines | Unmet dependencies |")
        out.append("|---|---:|---|")
        for f in sorted(remaining, key=lambda k: -counts[k]):
            unmet = ", ".join("`{}`".format(d) for d in sorted(remaining[f]))
            out.append("| `{}` | {} | {} |".format(f, counts[f], unmet))
        out.append("")

    out.append("## Layers")
    out.append("")
    for i, lz in enumerate(layers):
        out.append("### Layer {} — {} files, {} lines".format(
            i, len(lz), sum(counts[f] for f in lz)))
        out.append("")
        out.append("| File | Lines | Depends on |")
        out.append("|---|---:|---|")
        for f in sorted(lz, key=lambda k: -counts[k]):
            deps = ", ".join("`{}`".format(d) for d in sorted(graph[f])) or "—"
            out.append("| `{}` | {} | {} |".format(f, counts[f], deps))
        out.append("")

    os.makedirs("docs", exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))

    print("wrote {}".format(OUT))
    print("  {} files, {} lines".format(len(graph), total))
    print("  {} layers, {} files in cycles".format(len(layers), len(remaining)))


if __name__ == "__main__":
    main()
