"""
Train a character-level 4-gram language model on shell commands
and export the model data as an embeddable C++ header file.

Usage: python tools/train_ngram.py [corpus.txt] [output_header]
"""

import sys
import struct
import math
from collections import defaultdict

# ── Configuration ──────────────────────────────────────────────────────────
ORDER = 4  # 4-gram model (3 chars context predicts 4th)

# Characters we model (printable ASCII subset common in commands)
CHARS = (
    "abcdefghijklmnopqrstuvwxyz0123456789"
    "./-_=+\\:@~|&;(){}[]<>!$%^#*'\", "
)
CHAR_SET = set(CHARS)
START = '\x01'  # start-of-sequence marker
END = '\x02'    # end-of-sequence marker

def read_corpus(path):
    """Read command corpus, one command per line."""
    commands = []
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                commands.append(line)
    return commands

def tokenize(cmd):
    """Convert a command to a sequence of lowercase chars with start/end markers."""
    seq = [START]
    for ch in cmd.lower():
        if ch in CHAR_SET:
            seq.append(ch)
        else:
            seq.append(' ')  # replace uncommon chars with space
    seq.append(END)
    return seq

def count_ngrams(commands):
    """Count all 4-grams across all commands."""
    counts = defaultdict(int)
    for cmd in commands:
        seq = tokenize(cmd)
        for i in range(len(seq) - ORDER + 1):
            ngram = ''.join(seq[i:i + ORDER])
            counts[ngram] += 1
    return counts

def encode_ngram(ngram):
    """Pack a 4-char n-gram into a uint32_t."""
    return (ord(ngram[0]) << 24) | (ord(ngram[1]) << 16) | \
           (ord(ngram[2]) << 8) | ord(ngram[3])

def generate_header(commands, counts, output_path, name="ngram_model_data"):
    """Generate a C++ header with the embedded n-gram model data."""
    total_ngrams = sum(counts.values())

    # Sort entries by ngram value for binary search
    entries = sorted([
        (encode_ngram(ng), cnt)
        for ng, cnt in counts.items()
    ], key=lambda x: x[0])

    # Build context index: for each 3-char context, find the range of matching entries
    context_map = {}
    for i, (encoded_ng, cnt) in enumerate(entries):
        context = (encoded_ng >> 8) & 0xFFFFFF  # first 3 chars
        if context not in context_map:
            context_map[context] = [i, i]  # [start, end]
        context_map[context][1] = i

    # Calculate total unique characters
    unique_chars = sorted(CHAR_SET | {START, END})
    char_index = {c: i for i, c in enumerate(unique_chars)}

    lines = []
    lines.append(f"// Auto-generated 4-gram language model data")
    lines.append(f"// Corpus: {len(commands)} commands, {total_ngrams} total 4-grams, {len(entries)} unique")
    lines.append(f"// Generated by tools/train_ngram.py")
    lines.append(f"#ifndef WSH_NGRAM_MODEL_DATA_H")
    lines.append(f"#define WSH_NGRAM_MODEL_DATA_H")
    lines.append(f"")
    lines.append(f"#include <cstdint>")
    lines.append(f"")
    lines.append(f"namespace wsh {{")
    lines.append(f"")

    # ── Character set data ──
    lines.append(f"// Character set ({len(unique_chars)} chars)")
    lines.append(f"const int kCharCount = {len(unique_chars)};")
    lines.append(f"const char kChars[{len(unique_chars)}] = {{")
    for c in unique_chars:
        lines.append(f"    {ord(c):3d},  // '{c if c.isprintable() and c != START and c != END else '?'}'")
    lines.append(f"}};")
    lines.append(f"")

    # ── Entries data ──
    lines.append(f"// {len(entries)} n-gram entries, each: [uint32_t ngram][uint16_t count] = 6 bytes")
    lines.append(f"// Total: {len(entries) * 6} bytes")
    lines.append(f"const unsigned char kModelData[] = {{")
    hex_line = ""
    for encoded_ng, cnt in entries:
        packed = struct.pack(">IH", encoded_ng, cnt)  # big-endian uint32 + uint16
        hex_str = " ".join(f"0x{b:02X}," for b in packed)
        if len(hex_line) + len(hex_str) > 100:
            lines.append(f"    {hex_line}")
            hex_line = hex_str
        else:
            hex_line += hex_str
    if hex_line:
        lines.append(f"    {hex_line}")
    lines.append(f"}};")
    lines.append(f"")
    lines.append(f"const int kModelDataSize = sizeof(kModelData);")
    lines.append(f"const int kModelOrder = {ORDER};")
    lines.append(f"const int kModelNumEntries = {len(entries)};")
    lines.append(f"const int kModelTotalCount = {total_ngrams};")
    lines.append(f"")

    # ── Context index (maps 3-char context → entry range) ──
    sorted_contexts = sorted(context_map.items())
    lines.append(f"// Context index: {len(sorted_contexts)} unique 3-char contexts")
    lines.append(f"struct ContextEntry {{ uint32_t context; uint16_t start; uint16_t end; }};")
    lines.append(f"const ContextEntry kContextIndex[{len(sorted_contexts)}] = {{")
    for ctx, (s, e) in sorted_contexts:
        lines.append(f"    {{ 0x{ctx:06X}, {s}, {e} }},")
    lines.append(f"}};")
    lines.append(f"const int kContextIndexSize = {len(sorted_contexts)};")
    lines.append(f"")

    # ── Prior probabilities (for smoothing) ──
    lines.append(f"// Character prior probabilities (Laplace smoothing)")
    lines.append(f"const uint32_t kCharPrior[{len(unique_chars)}] = {{")
    for c in unique_chars:
        # Count how many times this char appears as the predicted char
        cnt = sum(v for ng, v in counts.items() if ng[3] == c)
        lines.append(f"    {cnt},")
    lines.append(f"}};")
    lines.append(f"")

    lines.append(f"}}  // namespace wsh")
    lines.append(f"")
    lines.append(f"#endif  // WSH_NGRAM_MODEL_DATA_H")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Generated {output_path}")
    print(f"  Commands: {len(commands)}")
    print(f"  Total 4-grams: {total_ngrams}")
    print(f"  Unique 4-grams: {len(entries)}")
    print(f"  Unique 3-char contexts: {len(sorted_contexts)}")
    print(f"  Data size: {len(entries) * 6} bytes + {len(sorted_contexts) * 10} bytes index")
    print(f"  Unique chars: {len(unique_chars)}")

def main():
    corpus_path = sys.argv[1] if len(sys.argv) > 1 else "tools/command_corpus.txt"
    output_path = sys.argv[2] if len(sys.argv) > 2 else "src/ai/providers/ngram_model_data.h"

    commands = read_corpus(corpus_path)
    print(f"Read {len(commands)} commands from {corpus_path}")

    counts = count_ngrams(commands)
    print(f"Counted {len(counts)} unique 4-grams")

    generate_header(commands, counts, output_path)
    print("Done!")

if __name__ == "__main__":
    main()
